name: motolisto
description: "A new Flutter project."

publish_to: 'none'

version: 0.0.3+3

environment:
  sdk: ^3.5.4

dependencies:
  bloc: ^8.1.4
  cloud_firestore: ^5.5.1
  cloud_functions: ^5.2.0
  cupertino_icons: ^1.0.8
  firebase_analytics: ^11.3.6
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1
  firebase_messaging: ^15.0.0
  firebase_remote_config: ^5.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_form_builder: ^9.5.0
  flutter_local_notifications: ^18.0.1
  form_builder_validators: ^11.0.0
  geoflutterfire_plus: ^0.0.32
  geolocator: ^13.0.2
  http: ^1.2.2
  hydrated_bloc: ^9.1.5
  image_picker: ^1.1.2
  intl_phone_number_input: ^0.7.4
  package_info_plus: ^8.1.2
  path_provider: ^2.1.5
  pinput: ^5.0.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
flutter_launcher_icons:
  image_path: "assets/icons/launcher_icon.png"
  adaptive_icon_foreground: "assets/icons/adaptive_launcher_icon.png"
  adaptive_icon_background: "#f2f2f2"
  android: true
  ios: true
  remove_alpha_ios: true
