// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIriRfn10kMwdB1dJYZqANqD8lrzKL1kk',
    appId: '1:723023185227:web:d1dcca506c4be2a8e094ce',
    messagingSenderId: '723023185227',
    projectId: 'moto-listo',
    authDomain: 'moto-listo.firebaseapp.com',
    storageBucket: 'moto-listo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANFCK4RHnbKjE0-HN2Y1Ph-9wTlhnm7ME',
    appId: '1:723023185227:android:984ce9d169918c76e094ce',
    messagingSenderId: '723023185227',
    projectId: 'moto-listo',
    storageBucket: 'moto-listo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADQgsmIo_s9Jxp8l2fHqzeAmndmN_QUBU',
    appId: '1:723023185227:ios:065ff2163bcf4227e094ce',
    messagingSenderId: '723023185227',
    projectId: 'moto-listo',
    storageBucket: 'moto-listo.firebasestorage.app',
    iosBundleId: 'com.example.motolisto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADQgsmIo_s9Jxp8l2fHqzeAmndmN_QUBU',
    appId: '1:723023185227:ios:065ff2163bcf4227e094ce',
    messagingSenderId: '723023185227',
    projectId: 'moto-listo',
    storageBucket: 'moto-listo.firebasestorage.app',
    iosBundleId: 'com.example.motolisto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIriRfn10kMwdB1dJYZqANqD8lrzKL1kk',
    appId: '1:723023185227:web:037e32990c961d8ce094ce',
    messagingSenderId: '723023185227',
    projectId: 'moto-listo',
    authDomain: 'moto-listo.firebaseapp.com',
    storageBucket: 'moto-listo.firebasestorage.app',
  );
}
